### ISSUE TITLE
Rename default appsettings.json file to local.settings.json

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-cli#122]
We've gotten feedback from customers that the name `appsettings.json` is confusing. I did a poll on the Advisors group. We got 50+ responses, with most voting for the name `local.settings.json`.

We should do the following:
- Change the default file that is created on func init 
- On all commands that use the settings file (e.g. func host start, func settings), print a deprecation warning if appsettings.json is used
  > Warning: The filename 'appsettings.json' is deprecated. Rename it to local.settings.json
- If both files exist, print a warning
  > Warning: found both 'local.settings.json' and 'appsettings.json'. Ignoring 'appsettings.json'.

**Comment by nitro52** [comment]
I got the warning so i renamed appsettings.json to local.settings.json. This worked fine. Then i tried connecting to azure using the "func azure login" commands and "func azure functionapp fetch" which created a new appsettings.json instead of updating local.settings.json. I manually copied into local.settings.json. but it seems that the cli commands still expect appsettings.json. 

has this been fixed just not released?

**Comment by lindydonna** [comment]
@nitro52 It was supposed to be released with the fix you mentioned, but it looks like we missed a code path. Thanks for the bug report! 

Reopening issue.

**Comment by ahmelsayed** [comment]
I can't repro this. `func azure functionapp fetch` puts the settings correctly in my local.settings.json. Are you sure you're using the latest 96 release?

**Comment by lindydonna** [comment]
@nitro52 Same here, it all works correctly on Beta96. Closing issue, let us know if you have an updated repro.

**Comment by nitro52** [comment]
Sorry guys, i did a npm i -g azure-functions-core-tools a day or two a go, at least i thought i did. seems like i was on 94 not 96. Updated and it looks fine.

**Comment by lindydonna** [comment]
@nitro52 thanks for confirming
