### ISSUE TITLE
CLI enable local http handlers from extensions 

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-functions-cli#197]
CLIR should set this envir var: 
  WEBSITE_HOSTNAME  = localhost:7071

Where 7071 is the port. 
This will enable extensions local http handling, which is used by DTF's 202 hook. 

This will mitigate  https://github.com/Azure/azure-webjobs-sdk-script/issues/1658

**Comment by lindydonna** [comment]
@ahmelsayed I've added to the next milestone since it should be an easy fix.

**Comment by adamavenant** [comment]
I have an issue with Function Proxies running locally through the CLI. I use WEBSITE_HOSTNAME to build the backendUri in proxies.json to avoid having to transform the file across environments. On local, this returns 0.0.0.0:71 and the redirect to the function fails as a result. 

It does not appear to be possible to override the value using local.settings.json (duplicate key error) and we don't want to add a custom variable because it creates a management overhead. 

Is there a more appropriate variable or approach to use? 

If appropriate, I can raise a bug for this. I am posting here first as I can see that there has been some discussion around the variable. Thank you.
