### ISSUE TITLE
Support same experience for PreCompiled Azure Functions as for csx Azure Functions

### ISSUE THREAD

**Issue by mkamonster** [Azure/azure-functions-cli#61]
I started out using C# script functions which has a very nice experience when you save the .csx file it will be reloaded by the Azure Function host. Because I had needed a more solid solution I moved over to PreCompiled Azure Functions (like https://github.com/Azure/azure-webjobs-sdk-script/wiki/Precompiled-functions).

There are actually two pieces that can have some experience improvements.

1: Right now I have a postbuild action to do a robocopy of the build output towards the Azure Function folder. It would be nice if this association is supported by tooling instead of a manual post build action. That would also enable the trigger the actual build of the PreCompiled Function when running the Azure Function project.

2: Because I now use a post-build step to copy the PreCompiled Function I noticed that I'm not able to update the dlls. They are locked when the Azure Function host is running. It would be a very nice experience if the dlls of the PreCompiled function can just be copied and even trigger a reload in the Azure Function Host.

**Comment by lindydonna** [comment]
@mkamonster Agreed on both counts!  For #1, we have an open issue for the Visual Studio tooling to support project references (https://github.com/Azure/Azure-Functions/issues/90). There's a build dependency workaround here: https://github.com/Azure/Azure-Functions/issues/90#issuecomment-272027522.

For #2, the fix is done but just needs to be deployed (which will be "soon" but I don't have an exact ETA). See https://github.com/Azure/azure-webjobs-sdk-script/commit/661e8de8449865139d20fe019f789a65cfe5da33.

If you want the latest fix locally, you can build the CLI project and swap in the build artifacts from the -Script AppVeyor build: https://ci.appveyor.com/project/appsvc/azure-webjobs-sdk-script-y8o14/history

Closing as duplicate.
