### ISSUE TITLE
Re-enable creation of function apps

### ISSUE THREAD

**Issue by Zazcallabah** [Azure/azure-functions-cli#78]
The following  issues were closed with the reasoning that the functionality has been moved to azure-cli:

- https://github.com/Azure/azure-functions-cli/issues/75
- https://github.com/Azure/azure-functions-cli/issues/50

However, azure cli does not contain the expected functionality: https://github.com/Azure/azure-cli/issues/2352

Thus: There is currently no way to create azure function apps using the command line. This tool was the only way. Now there is none. You removed it. Please re-add it.

**Comment by ahmelsayed** [comment]
@lindydonna

**Comment by lindydonna** [comment]
@Zazcallabah Unfortunately you'll have to wait for the functionality in the Azure CLI, which is coming soon. We don't want to add it to the Azure Functions CLI now, since we'd remove it as soon as it was part of the Azure CLI.

For now, you can create a function app by using the `az appservice web` commands and manually setting up the storage account connection string. The required properties are listed here: https://github.com/Azure/azure-quickstart-templates/blob/master/101-function-app-create-dynamic/azuredeploy.json#L62

**Comment by lindydonna** [comment]
Closing in favor of https://github.com/Azure/azure-cli/issues/2352
